from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Dict, List, Tuple

import numpy as np
from PIL import Image


def _load_tf():
    # Import TensorFlow lazily to keep app startup snappy.
    import tensorflow as tf  # type: ignore

    return tf


_MODEL_CACHE = {"path": None, "model": None}
_THRESHOLD_CACHE: Dict[str, Any] = {}


def _preprocess_image(image_path: Path, target_size: Tuple[int, int] = (64, 64)) -> np.ndarray:
    img = Image.open(image_path).convert("RGB")
    img = img.resize(target_size)
    arr = np.asarray(img, dtype=np.float32) / 255.0
    arr = np.expand_dims(arr, axis=0)  # (1, H, W, C)
    return arr


def _preprocess_rgb_frame(frame_rgb: np.ndarray, target_size: Tuple[int, int] = (64, 64)) -> np.ndarray:
    """
    frame_rgb: uint8 array (H, W, 3) in RGB order
    """
    img = Image.fromarray(frame_rgb).resize(target_size)
    arr = np.asarray(img, dtype=np.float32) / 255.0
    arr = np.expand_dims(arr, axis=0)
    return arr


def ensure_model_ready(model_path: Path) -> None:
    """
    Ensures `model_path` exists and is loadable.
    If missing or invalid, trains a tiny demo model and saves it.
    """
    model_path = Path(model_path)
    model_path.parent.mkdir(parents=True, exist_ok=True)

    if not model_path.exists() or model_path.stat().st_size == 0:
        _train_demo_model(model_path)
        return

    try:
        _get_model(model_path)
    except Exception:
        # If the file exists but is corrupted/invalid, recreate it.
        _train_demo_model(model_path)


def _train_demo_model(model_path: Path) -> None:
    from .train_model import train_and_save

    # If user provided a dataset path, train on it; otherwise keep synthetic demo.
    data_dir = os.environ.get("ASD_DATA_DIR") or os.environ.get("DATA_DIR") or None
    train_and_save(output_path=model_path, data_dir=data_dir, epochs=3, img_size=64, threshold=0.5)
    # Clear cache so next load uses the new file
    _MODEL_CACHE["path"] = None
    _MODEL_CACHE["model"] = None


def _load_threshold(model_path: Path) -> float:
    """
    Reads threshold from `model/threshold.json` generated by `train_model.py`.
    Fallback: 0.5
    """
    model_path = Path(model_path)
    key = str(model_path)
    if key in _THRESHOLD_CACHE:
        return float(_THRESHOLD_CACHE[key].get("threshold", 0.5))

    threshold_path = model_path.parent / "threshold.json"
    if not threshold_path.exists():
        _THRESHOLD_CACHE[key] = {"threshold": 0.5}
        return 0.5

    try:
        payload = json.loads(threshold_path.read_text(encoding="utf-8"))
        threshold = float(payload.get("threshold", 0.5))
    except Exception:
        threshold = 0.5

    _THRESHOLD_CACHE[key] = {"threshold": threshold}
    return threshold


def _get_model(model_path: Path):
    model_path = Path(model_path).resolve()
    if _MODEL_CACHE["model"] is not None and _MODEL_CACHE["path"] == str(model_path):
        return _MODEL_CACHE["model"]

    tf = _load_tf()
    model = tf.keras.models.load_model(str(model_path))
    _MODEL_CACHE["model"] = model
    _MODEL_CACHE["path"] = str(model_path)
    return model


def predict_image(image_path: Path, model_path: Path) -> Dict[str, Any]:
    """
    Returns:
      - label: "ASD Detected" / "No ASD"
      - confidence: float (0..1)
      - asd_probability: float (0..1)
      - threshold: float
    """
    image_path = Path(image_path)
    model_path = Path(model_path)

    x = _preprocess_image(image_path)
    model = _get_model(model_path)

    # Model outputs sigmoid probability for "ASD"
    prob_asd = float(model.predict(x, verbose=0)[0][0])
    threshold = _load_threshold(model_path)

    label = "ASD Detected" if prob_asd >= threshold else "No ASD"
    confidence = prob_asd if prob_asd >= threshold else (1.0 - prob_asd)

    return {
        "label": label,
        "confidence": round(confidence, 4),
        "asd_probability": round(prob_asd, 4),
        "threshold": threshold,
    }


def _sample_frame_indices(frame_count: int, max_frames: int) -> List[int]:
    if frame_count <= 0:
        return []
    if frame_count <= max_frames:
        return list(range(frame_count))

    # Evenly spaced indices across the video
    idxs = np.linspace(0, frame_count - 1, num=max_frames, dtype=int)
    return idxs.tolist()


def _roi(frame: np.ndarray, x0: float, y0: float, x1: float, y1: float) -> np.ndarray:
    """
    Crops a region of interest using fractional coords.
    frame: (H, W) or (H, W, C)
    """
    h, w = frame.shape[:2]
    xa = max(0, min(w - 1, int(x0 * w)))
    xb = max(0, min(w, int(x1 * w)))
    ya = max(0, min(h - 1, int(y0 * h)))
    yb = max(0, min(h, int(y1 * h)))
    if xb <= xa or yb <= ya:
        return frame
    return frame[ya:yb, xa:xb]


def _motion_score(prev_gray: np.ndarray, gray: np.ndarray, roi_box) -> float:
    """
    Simple motion energy score in [0..1] from frame-to-frame absolute difference.
    roi_box: (x0,y0,x1,y1) in fractional coordinates.
    """
    a = _roi(prev_gray, *roi_box).astype(np.float32)
    b = _roi(gray, *roi_box).astype(np.float32)

    # Resize to same shape if ROI math produced minor differences
    if a.shape != b.shape:
        h = min(a.shape[0], b.shape[0])
        w = min(a.shape[1], b.shape[1])
        a = a[:h, :w]
        b = b[:h, :w]

    diff = np.mean(np.abs(a - b)) / 255.0  # 0..1-ish
    # Map small diffs to low score, larger to high score smoothly.
    k = 6.0
    score = 1.0 - float(np.exp(-k * diff))
    return float(np.clip(score, 0.0, 1.0))


def _combined_label(prob: float, threshold: float = 0.5) -> Tuple[str, float]:
    label = "ASD Detected" if prob >= threshold else "No ASD"
    confidence = prob if prob >= threshold else (1.0 - prob)
    return label, confidence


def predict_video(video_path: Path, model_path: Path, max_frames: int = 16) -> Dict[str, Any]:
    """
    Loads a video, samples up to `max_frames` frames, predicts on each frame,
    then returns the average ASD probability.

    Requires: opencv-python
    """
    video_path = Path(video_path)
    model_path = Path(model_path)

    import cv2  # type: ignore

    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise ValueError("Could not open video. Try a different format (mp4/webm).")

    frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
    idxs = _sample_frame_indices(frame_count, max_frames=max_frames)

    if not idxs:
        # Some codecs don't provide frame count reliably; fall back to sequential sampling.
        idxs = list(range(max_frames))

    model = _get_model(model_path)
    probs: List[float] = []
    eye_scores: List[float] = []
    face_scores: List[float] = []
    behavior_scores: List[float] = []

    prev_gray = None

    for idx in idxs:
        # Seek (works for most formats; if not, OpenCV will approximate)
        cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
        ok, frame_bgr = cap.read()
        if not ok or frame_bgr is None:
            continue

        frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)

        # Motion-based (very lightweight) proxies for:
        # - eye movement: upper-middle region
        # - facial expression: central region
        # - behaviour: full-frame motion (gross movement)
        gray = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2GRAY)
        if prev_gray is not None:
            eye_scores.append(_motion_score(prev_gray, gray, roi_box=(0.30, 0.12, 0.70, 0.35)))
            face_scores.append(_motion_score(prev_gray, gray, roi_box=(0.22, 0.20, 0.78, 0.75)))
            behavior_scores.append(_motion_score(prev_gray, gray, roi_box=(0.00, 0.00, 1.00, 1.00)))
        prev_gray = gray

        x = _preprocess_rgb_frame(frame_rgb)
        prob_asd = float(model.predict(x, verbose=0)[0][0])
        probs.append(prob_asd)

    cap.release()

    if not probs:
        raise ValueError("Could not read frames from this video.")

    prob_asd_avg = float(np.mean(probs))
    eye = float(np.mean(eye_scores)) if eye_scores else 0.0
    face = float(np.mean(face_scores)) if face_scores else 0.0
    behavior = float(np.mean(behavior_scores)) if behavior_scores else 0.0

    # Combine: CNN probability + the three video-derived signals.
    # We keep CNN as the main term, and add a small contribution from each signal.
    combined_prob = float(
        np.clip((0.70 * prob_asd_avg) + (0.10 * eye) + (0.10 * face) + (0.10 * behavior), 0.0, 1.0)
    )

    threshold = _load_threshold(model_path)
    label, confidence = _combined_label(combined_prob, threshold=threshold)

    # Provide separate labels/confidences per category too
    eye_label, eye_conf = _combined_label(eye, threshold=threshold)
    face_label, face_conf = _combined_label(face, threshold=threshold)
    behavior_label, behavior_conf = _combined_label(behavior, threshold=threshold)

    return {
        "label": label,
        "confidence": round(confidence, 4),
        "asd_probability": round(combined_prob, 4),
        "threshold": threshold,
        "frames_used": len(probs),
        "signals": {
            "eye_movement": {
                "label": eye_label,
                "accuracy": round(eye_conf, 4),
                "score": round(eye, 4),
            },
            "facial_expression": {
                "label": face_label,
                "accuracy": round(face_conf, 4),
                "score": round(face, 4),
            },
            "behaviour": {
                "label": behavior_label,
                "accuracy": round(behavior_conf, 4),
                "score": round(behavior, 4),
            },
            "cnn_frame_avg": round(prob_asd_avg, 4),
        },
    }

